/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vidyayug.mobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MobileUserDetails service. Represents a row in the &quot;Mobile_userdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vidyayug.mobile.model.impl.MobileUserDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vidyayug.mobile.model.impl.MobileUserDetailsImpl}.
 * </p>
 *
 * @author MVIDYA
 * @see MobileUserDetails
 * @see com.vidyayug.mobile.model.impl.MobileUserDetailsImpl
 * @see com.vidyayug.mobile.model.impl.MobileUserDetailsModelImpl
 * @generated
 */
public interface MobileUserDetailsModel extends BaseModel<MobileUserDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mobile user details model instance should use the {@link MobileUserDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this mobile user details.
	 *
	 * @return the primary key of this mobile user details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mobile user details.
	 *
	 * @param primaryKey the primary key of this mobile user details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this mobile user details.
	 *
	 * @return the user ID of this mobile user details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this mobile user details.
	 *
	 * @param userId the user ID of this mobile user details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mobile user details.
	 *
	 * @return the user uuid of this mobile user details
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this mobile user details.
	 *
	 * @param userUuid the user uuid of this mobile user details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this mobile user details.
	 *
	 * @return the company ID of this mobile user details
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this mobile user details.
	 *
	 * @param companyId the company ID of this mobile user details
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the email of this mobile user details.
	 *
	 * @return the email of this mobile user details
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this mobile user details.
	 *
	 * @param email the email of this mobile user details
	 */
	public void setEmail(String email);

	/**
	 * Returns the username of this mobile user details.
	 *
	 * @return the username of this mobile user details
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this mobile user details.
	 *
	 * @param username the username of this mobile user details
	 */
	public void setUsername(String username);

	/**
	 * Returns the password of this mobile user details.
	 *
	 * @return the password of this mobile user details
	 */
	public long getPassword();

	/**
	 * Sets the password of this mobile user details.
	 *
	 * @param password the password of this mobile user details
	 */
	public void setPassword(long password);

	/**
	 * Returns the street of this mobile user details.
	 *
	 * @return the street of this mobile user details
	 */
	@AutoEscape
	public String getStreet();

	/**
	 * Sets the street of this mobile user details.
	 *
	 * @param street the street of this mobile user details
	 */
	public void setStreet(String street);

	/**
	 * Returns the city of this mobile user details.
	 *
	 * @return the city of this mobile user details
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this mobile user details.
	 *
	 * @param city the city of this mobile user details
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this mobile user details.
	 *
	 * @return the state of this mobile user details
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this mobile user details.
	 *
	 * @param state the state of this mobile user details
	 */
	public void setState(String state);

	/**
	 * Returns the zipcode of this mobile user details.
	 *
	 * @return the zipcode of this mobile user details
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this mobile user details.
	 *
	 * @param zipcode the zipcode of this mobile user details
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the phone number of this mobile user details.
	 *
	 * @return the phone number of this mobile user details
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this mobile user details.
	 *
	 * @param phoneNumber the phone number of this mobile user details
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the create date of this mobile user details.
	 *
	 * @return the create date of this mobile user details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this mobile user details.
	 *
	 * @param createDate the create date of this mobile user details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mobile user details.
	 *
	 * @return the modified date of this mobile user details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mobile user details.
	 *
	 * @param modifiedDate the modified date of this mobile user details
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MobileUserDetails mobileUserDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MobileUserDetails> toCacheModel();

	@Override
	public MobileUserDetails toEscapedModel();

	@Override
	public MobileUserDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}